-- TOÀN BỘ CẤU TRÚC DATABASE CHO ỨNG DỤNG ĐẶT PHÒNG KHÁCH SẠN
-- Hướng dẫn: Copy toàn bộ nội dung này dán vào SQL Editor của Supabase và nhấn RUN.

-- 1. Tạo bảng Users
CREATE TABLE users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text,
  password text not null,
  role text default 'user',
  full_name text,
  phone text
);

-- 2. Tạo bảng Hotels
CREATE TABLE hotels (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  description text,
  amenities text,
  image_url text,
  gallery text
);

-- 3. Tạo bảng Rooms
CREATE TABLE rooms (
  id bigint generated by default as identity primary key,
  hotel_id bigint references hotels(id) on delete cascade,
  room_number text not null,
  type text,
  price float8 not null,
  status text default 'Available' -- 'Available', 'Occupied', 'Maintenance'
);

-- 4. Tạo bảng Bookings
CREATE TABLE bookings (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade,
  room_id bigint references rooms(id) on delete cascade,
  check_in_date timestamp with time zone,
  check_out_date timestamp with time zone,
  total_price float8,
  status text default 'Pending', -- 'Pending', 'Confirmed', 'Checked-in', 'Completed', 'Cancelled'
  payment_proof_url text,
  payment_method text default 'Online'
);

-- 5. Tạo bảng Reviews
CREATE TABLE reviews (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade,
  hotel_id bigint references hotels(id) on delete cascade,
  rating int check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamp with time zone default now()
);

-- 6. Tạo bảng Settings
CREATE TABLE settings (
  key text primary key,
  value text
);

-- --- DỮ LIỆU MẪU ---
INSERT INTO users (username, email, password, role, full_name)
VALUES ('admin', 'admin@hotel.com', '123', 'admin', 'Quản trị viên');

INSERT INTO settings (key, value)
VALUES ('qr_code_url', 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=STK_DEFAULT');

-- Thêm một khách sạn mẫu
INSERT INTO hotels (name, location, description, amenities, image_url)
VALUES ('The Imperial Hotel', 'Vũng Tàu', 'Khách sạn phong cách Victoria sang trọng.', 'Bãi biển riêng, Hồ bơi', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800');
